image: Visual Studio 2017
configuration: Release
platform: x64

install:
 - appveyor DownloadFile https://vulkan.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
 - vulkan-sdk.exe

build:
  project: amf/public/samples/CPPSamples_vs2017.sln

artifacts:
    - path: bin\Release\*.*
      name: $(APPVEYOR_PROJECT_NAME)

deploy:
  - provider: GitHub
    artifact: $(APPVEYOR_PROJECT_NAME)
    auth_token:
      secure: 'hY5Mk6KOwgQ97TzEBsM7Woqr1ZIm5QTvHg8EvxMV1x8j3wk/3mNBMqWFFbEIBK0i'
    prerelease: true
    on:
      appveyor_repo_tag: true
